### https://www.baeldung.com/ops/kafka-docker-setup
### https://github.com/confluentinc/demo-scene/blob/master/community-components-only/docker-compose.yml#L22-L51

version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_network
    volumes:
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

  as0:
    build: .
    depends_on:
      - kafka
    networks:
      - kafka_network
    restart: on-failure
    container_name: as0
    environment:
      AS_SIZE: 100
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      AS_NAME: as0
      EVAL_SIMULATED_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_0_traffic-5.pcap
      EVAL_SIMULATED_ATK_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_0_attack_traffic-5.pcap
      MANAGED_IPS_PATH: ./eval_data/managed_ips/AS_0_managed_ip_10000.txt

  as1:
    build: .
    depends_on:
      - kafka
    networks:
      - kafka_network
    restart: on-failure
    container_name: as1
    environment:
      AS_SIZE: 100
      AS_NAME: as1
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      EVAL_SIMULATED_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_1_traffic-5.pcap
      EVAL_SIMULATED_ATK_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_1_attack_traffic-5.pcap
      MANAGED_IPS_PATH: ./eval_data/managed_ips/AS_1_managed_ip_10000.txt

  as2:
    build: .
    depends_on:
      - kafka
    networks:
      - kafka_network
    restart: on-failure
    container_name: as2
    environment:
      AS_SIZE: 100
      AS_NAME: as2
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      EVAL_SIMULATED_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_2_traffic-5.pcap
      EVAL_SIMULATED_ATK_TRAFFIC_PATH: ./eval_data/traffic_files/burst/AS_2_attack_traffic-5.pcap
      MANAGED_IPS_PATH: ./eval_data/managed_ips/AS_2_managed_ip_10000.txt


networks:
  kafka_network:
    name: kafka_network